### ISSUE TITLE
No handle drawn to SplitLayout created with Flow API of 14 RC3 in Lumo themed application

### ISSUE THREAD

**Issue by alump** [vaadin/vaadin-split-layout-flow#68]
No handle drawn when using SplitLayout with Java API on 14 RC3 application. Tested with Chrome, Firefox and Safari. And also tested by defining theme variants, no changes. Handle is not drawn.

There is anyway area from where user can adjust split by dragging it. So this looks like theming issue?

I assume split panel should look similar to https://vaadin.com/components/vaadin-split-layout/java-examples

**Comment by alump** [comment]
My setup:
- Spring Boot starter 14 RC3
- Amazon Corretto 11
- Maven 3.6.1
- Running with `spring-boot:run`
- Code:
```
        SplitLayout layout = new SplitLayout(
                new Label("First content component"),
                new Label("Second content component"));
        layout.setWidth("100%");
        layout.setHeight("400px");
        add(layout);
```

**Comment by alump** [comment]
It looks like split layout's shadow dom's handle part doesn't have after css rule at all with Lumo.

**Comment by alump** [comment]
<img width="600" alt="Screen Shot 2019-07-05 at 16 47 41" src="https://user-images.githubusercontent.com/1378660/60748633-ae289b00-9f44-11e9-9305-5f54e1536c83.png">

This is CSS rules inside vaadin-split-panel, no rule defined for `[part="handle"]::after`

**Comment by alump** [comment]
It start to feel like there is something wrong with vaadin-split-layout, as it's also not found by designer: https://github.com/vaadin/designer/issues/2085

**Comment by web-padawan** [comment]
According to https://github.com/vaadin/designer/issues/2085#issuecomment-511991840 the problem was fixed in Designer. 
No one else has reported this bug. So I assume we can close this.
