### ISSUE TITLE
Unable to get rid of width when moving component out of SplitLayout

### ISSUE THREAD

**Issue by guttormvik** [vaadin/vaadin-split-layout-flow#75]
This is an issue in Vaadin 14.1.17

I'm using AppLayout, and on the right-hand side I'm going to have a silimar drawer to that AppLayout has on the left.

I have a button to toggle it on/off.
This takes the AppLayout content and replaces with new SplitLayout(appLayout.getContent(), rightDrawer);
When hiding, I do appLayout.setContent(splitLayout.getPrimaryComponent())
This works fine, *but* as soon as I set the split position, I can't get rid of it again.

When I create the split, the left side get "width: 80%" and the right get "width: 20%", which is expected.
When I remove the split, and set left side of split as appLayout content, the "width: 80%" remains.
It doesn't help to do setWidthFull()

If I set border as part of the toggle, that *is* propagated to the client, and if I use debugger check the content of getElement().getStyle() it has the expected width=100%.
It seems it is reset to 80% again after my split routine is done, but by what?

[SplitView.zip](https://github.com/vaadin/platform/files/4262487/SplitView.zip)

**Comment by juhopiirainen** [comment]
Hi @guttormvik! Thanks for the issue. I have transfered it to the team for investigations.

**Comment by guttormvik** [comment]
One workaround, found by Johannes@vaadin:

Enable push (websocket) mode with @Push on view and:
sidebarWrapper.setSplitterPosition(100);
getUI().ifPresent(UI::push);

This is currently not applicable for us, since we don't use @Push mode

**Comment by rolfsmeds** [comment]
Possibly related to https://github.com/vaadin/vaadin-split-layout-flow/issues/47 ?

**Comment by rolfsmeds** [comment]
Another possible workaround could be to keep the SplitLayout even when the right-hand side component is not shown, and simply set the left side width to 100%.
